### PR TITLE
Build with GHC 9.12

### LINKED ISSUE #2: Code does not build with GHC 8.6.5, does not list which version of GHC is needed
```
$ make
ghc --make -o tc Main.hs -fwarn-incomplete-patterns -Werror

TypeChecker.hs:1:55: error: [-Werror]
    -XOverlappingInstances is deprecated: instead use per-instance pragmas OVERLAPPING/OVERLAPPABLE/OVERLAPS
  |
1 | {-# LANGUAGE UndecidableInstances, FlexibleInstances, OverlappingInstances #-}
  |                                                       ^^^^^^^^^^^^^^^^^^^^
make: *** [Makefile:25: tc] Error 1
```
If I disable that, I get
```
$ make ghc_flags=-fwarn-incomplete-patterns
make -C typechecker
make[1]: Entering directory '/home/jgross/Documents/GitHub/insane/typechecker'
ghc --make -o tc Main.hs -fwarn-incomplete-patterns

TypeChecker.hs:1:55: warning:
    -XOverlappingInstances is deprecated: instead use per-instance pragmas OVERLAPPING/OVERLAPPABLE/OVERLAPS
  |
1 | {-# LANGUAGE UndecidableInstances, FlexibleInstances, OverlappingInstances #-}
  |                                                       ^^^^^^^^^^^^^^^^^^^^

TypeChecker/Force.hs:1:55: warning:
    -XOverlappingInstances is deprecated: instead use per-instance pragmas OVERLAPPING/OVERLAPPABLE/OVERLAPS
  |
1 | {-# LANGUAGE FlexibleInstances, UndecidableInstances, OverlappingInstances #-}
  |                                                       ^^^^^^^^^^^^^^^^^^^^

TypeChecker/Print.hs:1:55: warning:
    -XOverlappingInstances is deprecated: instead use per-instance pragmas OVERLAPPING/OVERLAPPABLE/OVERLAPS
  |
1 | {-# LANGUAGE FlexibleInstances, UndecidableInstances, OverlappingInstances #-}
  |                                                       ^^^^^^^^^^^^^^^^^^^^

TypeChecker/DeBruijn.hs:1:55: warning:
    -XOverlappingInstances is deprecated: instead use per-instance pragmas OVERLAPPING/OVERLAPPABLE/OVERLAPS
  |
1 | {-# LANGUAGE FlexibleInstances, UndecidableInstances, OverlappingInstances #-}
  |                                                       ^^^^^^^^^^^^^^^^^^^^
[11 of 19] Compiling TypeChecker.Monad.Heap ( TypeChecker/Monad/Heap.hs, TypeChecker/Monad/Heap.o )

TypeChecker/Monad/Heap.hs:84:5: error:
    • Could not deduce (Control.Monad.Fail.MonadFail TC)
        arising from a do statement
        with the failable pattern ‘Evaluated x’
      from the context: Pointer ptr a
        bound by the type signature for:
                   forceClosure :: forall ptr a. Pointer ptr a => ptr -> TC a
        at TypeChecker/Monad/Heap.hs:82:1-44
    • In a stmt of a 'do' block: Evaluated x <- modClosure eval p
      In the expression:
        do Evaluated x <- modClosure eval p
           return x
      In an equation for ‘forceClosure’:
          forceClosure p
            = do Evaluated x <- modClosure eval p
                 return x
            where
                eval cl@(Evaluated _) = return cl
                eval (Unevaluated m)
                  = do x <- runTCClosure m
                       ....
   |
84 |     Evaluated x <- modClosure eval p
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
make[1]: *** [Makefile:25: tc] Error 1
make[1]: Leaving directory '/home/jgross/Documents/GitHub/insane/typechecker'
make: *** [Makefile:3: default] Error 2
```

What version of ghc should I be using?  Or would it be possible to update the project for newer ghc?

### PR DESCRIPTION
**Pull request by andreasabel**
- **Tabs to spaces**
  

- **Build with GHC 9.12**
  - MonadFail
  - Semigroup
  - mtl-2.3  (Error -> Except)
  

- **Add build information for cabal and stack**
  
Closes #2.

### CODE REVIEW

**Review by UlfNorell — APPROVED** [review]
Thanks 👍🏻
